export const keywords = [
  "manga",
  "mangapp",
  "komikcast",
  "komikcast.lol",
  "komikcast.moe",
  "mangaplus",
  "read comics",
  "mangap",
  "manga komik",
  "comics",
  "komik bahasa indonesia",
  "jujutsu kaisen",
  "naruto",
  "solo leveling",
  "wind breaker",
  "manga onepiece",
  "manga naruto",
  "manga jujutsu kaisen",
  "manhwa solo leveling",
  "manga bahasa indonesia",
  "komik online",
  "baca komik",
  "manga terbaru",
  "manhwa terbaru",
  "manhua terbaru",
  "download manga",
  "download komik",
  "baca manga online",
  "baca manhwa online",
  "baca manhua online",
  "komik gratis",
  "manga gratis",
  "manhwa gratis",
  "manhua gratis",
  "komik indonesia",
  "manga indonesia",
  "manhwa indonesia",
  "manhua indonesia",
  "baca manga bahasa indonesia",
  "baca manhwa bahasa indonesia",
  "baca manhua bahasa indonesia",
  "komik jujutsu kaisen",
  "komik naruto",
  "komik solo leveling",
  "komik wind breaker",
  "manga one piece",
  "komik one piece",
  "manga boruto",
  "komik boruto",
  "manga attack on titan",
  "komik attack on titan",
  "manga demon slayer",
  "komik demon slayer",
  "manga kimetsu no yaiba",
  "komik kimetsu no yaiba",
  "manga black clover",
  "komik black clover",
  "manga my hero academia",
  "komik my hero academia",
  "manga tokyo revengers",
  "komik tokyo revengers",
  "manga dr. stone",
  "komik dr. stone",
  "manga chainsaw man",
  "komik chainsaw man",
  "manga spy x family",
  "komik spy x family",
  "manga blue lock",
  "komik blue lock",
  "manga kingdom",
  "komik kingdom",
  "manga hunter x hunter",
  "komik hunter x hunter",
  "manga bleach",
  "komik bleach",
  "manga fairy tail",
  "komik fairy tail",
  "manga dragon ball",
  "komik dragon ball",
  "manga one punch man",
  "komik one punch man",
  "manga gintama",
  "komik gintama",
  "manga death note",
  "komik death note",
  "manga fullmetal alchemist",
  "komik fullmetal alchemist",
  "manga seven deadly sins",
  "komik seven deadly sins",
  "manga berserk",
  "komik berserk",
  "manga vagabond",
  "komik vagabond",
  "manga tokyo ghoul",
  "komik tokyo ghoul",
  "manga nanatsu no taizai",
  "komik nanatsu no taizai",
  "manga sword art online",
  "komik sword art online",
  "manga akame ga kill",
  "komik akame ga kill",
  "manga overlord",
  "komik overlord",
  "manga re:zero",
  "komik re:zero",
  "manga goblin slayer",
  "komik goblin slayer",
  "manga no game no life",
  "komik no game no life",
  "manga sao",
  "komik sao",
  "manga fate stay night",
  "komik fate stay night",
  "manga fate zero",
  "komik fate zero",
  "manga log horizon",
  "komik log horizon",
  "manga danmachi",
  "komik danmachi",
  "manga mahouka koukou no rettousei",
  "komik mahouka koukou no rettousei",
  "manga konosuba",
  "komik konosuba",
  "manga attack on titan junior high",
  "komik attack on titan junior high",
  "manga shingeki no kyojin",
  "komik shingeki no kyojin",
  "manga noragami",
  "komik noragami",
  "manga kakegurui",
  "komik kakegurui",
  "manga ajin",
  "komik ajin",
  "manga parasyte",
  "komik parasyte",
  "manga claymore",
  "komik claymore",
  "manga blood lad",
  "komik blood lad",
  "manga yowamushi pedal",
  "komik yowamushi pedal",
  "manga haikyuu",
  "komik haikyuu",
  "manga kuroko no basket",
  "komik kuroko no basket",
  "manga slam dunk",
  "komik slam dunk",
  "manga hajime no ippo",
  "komik hajime no ippo",
  "manga baki",
  "komik baki",
  "manga kengan ashura",
  "komik kengan ashura",
  "manga dorohedoro",
  "komik dorohedoro",
  "manga fire force",
  "komik fire force",
  "manga soul eater",
  "komik soul eater",
  "manga yuri on ice",
  "komik yuri on ice",
  "manga black bullet",
  "komik black bullet",
  "manga seraph of the end",
  "komik seraph of the end",
  "manga owari no seraph",
  "komik owari no seraph",
  "manga trigun",
  "komik trigun",
  "manga fate kaleid liner",
  "komik fate kaleid liner",
  "manga little busters",
  "komik little busters",
  "manga angel beats",
  "komik angel beats",
  "manga clannad",
  "komik clannad",
  "manga your lie in april",
  "komik your lie in april",
  "manga anohana",
  "komik anohana",
  "manga toradora",
  "komik toradora",
  "manga golden time",
  "komik golden time",
  "manga charlotte",
  "komik charlotte",
  "manga air gear",
  "komik air gear",
  "manga eyeshield 21",
  "komik eyeshield 21",
  "manga blue exorcist",
  "komik blue exorcist",
  "manga ao no exorcist",
  "komik ao no exorcist",
  "manga black lagoon",
  "komik black lagoon",
  "manga deadman wonderland",
  "komik deadman wonderland",
  "manga btooom",
  "komik btooom",
  "manga mirai nikki",
  "komik mirai nikki",
  "manga future diary",
  "komik future diary",
  "manga samurai champloo",
  "komik samurai champloo",
  "manga shokugeki no soma",
  "komik shokugeki no soma",
  "manga food wars",
  "komik food wars",
  "manga shaman king",
  "komik shaman king",
  "manga fairy tail",
  "komik fairy tail",
  "manga hunter x hunter",
  "komik hunter x hunter",
  "manga yuyu hakusho",
  "komik yuyu hakusho",
  "manga ranma 1/2",
  "komik ranma 1/2",
  "manga inuyasha",
  "komik inuyasha",
  "manga rurouni kenshin",
  "komik rurouni kenshin",
  "manga detective conan",
  "komik detective conan",
  "manga d.gray-man",
  "komik d.gray-man",
  "manga beelzebub",
  "komik beelzebub",
  "manga katekyo hitman reborn",
  "komik katekyo hitman reborn",
  "manga reborn",
  "komik reborn",
  "manga nurarihyon no mago",
  "komik nurarihyon no mago",
  "manga magi",
  "komik magi",
  "manga the labyrinth of magic",
  "komik the labyrinth of magic",
  "manga the kingdom of magic",
  "komik the kingdom of magic",
  "manga akatsuki no yona",
  "komik akatsuki no yona",
  "manga yona of the dawn",
  "komik yona of the dawn",
  "manga nisekoi",
  "komik nisekoi",
  "manga hyouka",
  "komik hyouka",
  "manga k-on",
  "komik k-on",
  "manga angel beats",
  "komik angel beats",
  "manga clannad",
  "komik clannad",
  "manga your lie in april",
  "komik your lie in april",
  "manga anohana",
  "komik anohana",
  "manga toradora",
  "komik toradora",
  "manga golden time",
  "komik golden time",
  "manga charlotte",
  "komik charlotte",
];
