import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import PopularList from "@/components/PopularList";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const url = `${process.env.API_URL}/popular`;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <div className="">

            <Navbar />
          </div>
          <div className="flex flex-col lg:flex-row p-5">
            <main className="flex-1 min-h-screen">
              {children}
            </main>
            <aside className="hidden lg:block lg:w-1/4 mr-4">
              <PopularList url={url} />
            </aside>
          </div>
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
